name: Commands
version: '${project.version}'
main: me.wiburach.custom_item.main
api-version: 1.16
authors: [ ditmekiwi ]
description: wibu rach
commands:
  heal:
    description: Hồi máu người chơi
    usage: /<command>
    aliases: healme
  feed:
    description: Hồi thức ăn người chơi
    usage: /<command>
    aliases: feedme
  feed:
    description: Spawn any mobs
    usage: /<command>
